package cse308.map.model;

public enum Measure {
    POPULATION_EQUALITY,
    EFFICIENCY_GAP,
    COMPACTNESS,
    PARTISAN_FAIRNESS,
    COMPETITIVENESS,
    GERRYMANDER_REPUBLICAN,
    GERRYMANDER_DEMOCRAT
}
